### ISSUE TITLE
Get translated verbose_name

### ISSUE THREAD

**Issue by mayait** [idlesign/django-etc#1]
All the items in my model are being translated by django.utils.translation
For example

```python
code = models.CharField(max_length=200, null=True, blank=True,  unique=True, 
help_text=_('Product catalog code unique identifier'),
verbose_name=_('Product Code'))
```

Is there any way to get the verbose_name string translated?

**Comment by idlesign** [comment]
That should work with `django.utils.translation.gettext_lazy`. 
If it doesn't, please describe when do you use `activate` language function.

**Comment by mayait** [comment]
It was my bad, is working with gettext_lazy on the model side imported as:
```python
from django.utils.translation import ugettext_lazy as _
```
It's Amazing!
