### ISSUE TITLE
AttributeError: module 'django.contrib.admin.models' has no attribute 'CharField'

### ISSUE THREAD

**Issue by kev26** [idlesign/django-etc#5]
In tutorial https://django-etc.readthedocs.io/en/latest/admin.html#tools-for-django-admin
Should be  `from django.db imprort models` instead of `from django.contrib.admin import models`

**Comment by idlesign** [comment]
Thank you. Yes.
Pull request is welcome: https://github.com/idlesign/django-etc/blob/master/docs/source/admin.rst
