### ISSUE TITLE
How to export csv file

### ISSUE THREAD

**Issue by kev26** [idlesign/django-etc#6]
Thank for the package useful for me, I created some Postgresql functions and I want to run it on Django admin then export CSV file, so this is my way, but in save(). Could I perform HttpResponse for export csv file ? Thank you
```python
class artist_report_card(CustomModelPage):
    title = 'Aritst report card'  # set page title

    # Define some fields.
    input_date = models.DateField()
    bound_admin = admins.CustomPageModelAdmin  # set admin class for this page

    def save(self):
        # Implement data handling from self attributes here.
        # self.bound_admin has some useful methods.
        # self.bound_request allows you to access current HTTP request.
        self.bound_admin.message_success(self.bound_request, f'Hey, done!')
        curr = connection.cursor()
        curr.execute(
            f"SELECT public.artist_report_card('{self.input_date}')")
        data = curr.fetchall()
        curr.close()
        response = self.bound_request.HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f"'attachment; filename={self.input_date}.csv'"
        for row in data:
        writer = csv.writer(response, delimiter=',')
        writer.writerow(row)
artist_report_card.register()
        ```

**Comment by idlesign** [comment]
Thank you.

You can try, for example, to put csv into an instance variable and override `CustomPageModelAdmin.response_add()` to respond with the contents of the variable wrapped in Response object.

**Comment by kev26** [comment]
> Thank you.
> 
> You can try, for example, to put csv into an instance variable and override `CustomPageModelAdmin.response_add()` to respond with the contents of the variable wrapped in Response object.

I really do not understand this. Could you explain this more clearly? Thank you

**Comment by idlesign** [comment]
Something like:

1. In your `artist_report_card.save()` put `reponse` into `self.my_response`.
2. Define your own class inherited from `CustomPageModelAdmin`. Eg. `MyAdmin`.
3. Override `MyAdmin.response_add()`, so that it returns your csv response, e.g. from `obj.my_response`.
4. Set `artist_report_card.bound_admin = MyAdmin`

**Comment by kev26** [comment]
> Something like:
> 
> 1. In your `artist_report_card.save()` put `reponse` into `self.my_response`.
> 2. Define your own class inherited from `CustomPageModelAdmin`. Eg. `MyAdmin`.
> 3. Override `MyAdmin.response_add()`, so that it returns your csv response, e.g. from `obj.my_response`.
> 4. Set `artist_report_card.bound_admin = MyAdmin`


`    bound_admin = MyAdmin  # set admin class for this page
NameError: name 'MyAdmin' is not defined`

```python
class aritst_report_card(CustomModelPage):
    title = 'Aritst report card'  # set page title

    # Define some fields.
    input_date = models.DateField()
    bound_admin = MyAdmin  # set admin class for this page

    def save(self):
        # Implement data handling from self attributes here.
        # self.bound_admin has some useful methods.
        # self.bound_request allows you to access current HTTP request.
        self.bound_admin.message_success(self.bound_request, f'Hey, done!')
        print(self.input_date)
        curr = connection.cursor()
        curr.execute(
            f"SELECT public.artist_report_card('{self.input_date}')")
        response = curr.fetchall()
        curr.close()
        self.my_response = response
        return self.my_response
        


class MyAdmin(admins.CustomPageModelAdmin):
    def response_add(self, request: HttpRequest, obj: 'CustomModelPage', post_url_continue=None):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f"'attachment; filename={self.input_date}.csv'"
        writer = csv.writer(response)
        for row in obj.my_response:
            print(row)
            writer = csv.writer(response)
            writer.writerow(row)
        return HttpResponseRedirect(request.path)

aritst_report_card.register()
```

**Comment by idlesign** [comment]
1. That's Python, so classes and vars should be defined before usage, not after.
2. You do not need to return anything from `.save()`.
3. And you don't need to return a redirect response from `.response_add()`. Return your `response` instead.

**Comment by kev26** [comment]
> 1. That's Python, so classes and vars should be defined before usage, not after.
> 2. You do not need to return anything from `.save()`.
> 3. And you don't need to return a redirect response from `.response_add()`. Return your `response` instead.

Thank, you, I fixed, but seem nothing happened 
```python
class MyAdmin(admins.CustomPageModelAdmin):
    def response_add(self, request: HttpRequest, obj: 'CustomModelPage', post_url_continue=None):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f"'attachment; filename={self.input_date}.csv'"
        writer = csv.writer(response)
        for row in obj.my_response:
            print(row)
            writer = csv.writer(response)
            writer.writerow(row)
        return response
class aritst_report_card(CustomModelPage):
    title = 'Aritst report card'  # set page title
    # Define some fields.
    input_date = models.DateField()
    bound_admin = MyAdmin  # set admin class for this page

    def save(self):
        curr = connection.cursor()
        curr.execute(
            f"SELECT public.artist_report_card('{self.input_date}')")
        response = curr.fetchall()
        curr.close()
        self.my_response = response
        self.bound_admin.message_success(self.bound_request, f'Hey, done!')

aritst_report_card.register()
```

**Comment by idlesign** [comment]
> Thank, you, I fixed, but seem nothing happened

You may open your browser console (F12) and see what response recieves your browser on save in admin.

**Comment by kev26** [comment]
> > Thank, you, I fixed, but seem nothing happened
> 
> You may open your browser console (F12) and see what response recieves your browser on save in admin.

seem problem from MyAdmin, I try to print `obj.my_response` then no result to response

**Comment by idlesign** [comment]
> seem problem from MyAdmin, I try to print obj.my_response then no result to response

Ah, I see. You probably don't use the latest code from this repository (for which docs are generated), but use package from PyPI. I'll try to release a new version on PyPI this week.

Having 1.3.1 from PyPI try to pass `admin_model` to `aritst_report_card.register()`, like:

```python
class MyAdmin(CustomPageModelAdmin):

    def response_add(self, request, obj: 'CustomModelPage', post_url_continue=None):
        return obj.my_response


class aritst_report_card(CustomModelPage):

    title = 'Aritst report card'
    input_date = models.DateField()

    def save(self):

        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f"'attachment; filename={self.input_date}.csv'"

        curr = connection.cursor()
        curr.execute(
            f"SELECT public.artist_report_card('{self.input_date}')")
        rows = curr.fetchall()
        curr.close()

        writer = csv.writer(response)
        for row in rows:
            writer.writerow(row)

        self.my_response = response

        self.bound_admin.message_success(self.bound_request, 'Hey, done!')

aritst_report_card.register(admin_model=MyAdmin)
```

**Comment by idlesign** [comment]
By the way, instead of `SELECT public.artist_report_card` use models and ORM whenever possible.

**Comment by kev26** [comment]
> > seem problem from MyAdmin, I try to print obj.my_response then no result to response
> 
> Ah, I see. You probably don't use the latest code from this repository (for which docs are generated), but use package from PyPI. I'll try to release a new version on PyPI this week.
> 
> Having 1.3.1 from PyPI try to pass `admin_model` to `aritst_report_card.register()`, like:
> 
> ```python
> class MyAdmin(CustomPageModelAdmin):
> 
>     def response_add(self, request, obj: 'CustomModelPage', post_url_continue=None):
>         return obj.my_response
> 
> 
> class aritst_report_card(CustomModelPage):
> 
>     title = 'Aritst report card'
>     input_date = models.DateField()
> 
>     def save(self):
> 
>         response = HttpResponse(content_type='text/csv')
>         response['Content-Disposition'] = f"'attachment; filename={self.input_date}.csv'"
> 
>         curr = connection.cursor()
>         curr.execute(
>             f"SELECT public.artist_report_card('{self.input_date}')")
>         rows = curr.fetchall()
>         curr.close()
> 
>         writer = csv.writer(response)
>         for row in rows:
>             writer.writerow(row)
> 
>         self.my_response = response
> 
>         self.bound_admin.message_success(self.bound_request, 'Hey, done!')
> 
> aritst_report_card.register(admin_model=MyAdmin)
> ```

Amazing, thank you so much !!!

**Comment by kev26** [comment]
> By the way, instead of `SELECT public.artist_report_card` use models and ORM whenever possible.

Thank you, the customer created these Postgres functions, so my task will implement it to Django admin for they use them
