### ISSUE TITLE
How to edit the template on new admin page

### ISSUE THREAD

**Issue by kev26** [idlesign/django-etc#7]
If I want to remove or edit these buttons, whether any way to do them? Thank so much.
![image](https://user-images.githubusercontent.com/25315610/193795556-8882df1e-b045-498e-8606-53ee9d820f8b.png)
![image](https://user-images.githubusercontent.com/25315610/193795631-9fefcc63-c5c8-4c6f-b07b-a1e27bd7ed02.png)

**Comment by idlesign** [comment]
This doesn't belong to `django-etc`. Please consult Django Admin contrib documentation.
